### ISSUE TITLE
`mpi4py`'s `concurrent.futures` implementation

### ISSUE THREAD

**Issue by jakirkham** [jan-janssen/pympipool#3]
Perhaps this is already known, but it is a bit buried in the docs. So thought it would be worthwhile to surface in case it may be of interest.

Within `mpi4py`, there is a [`concurrent.futures` implementation of `Executor`s]( https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html ). These include a [MPI-2 based implementation]( https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html#mpipoolexecutor ) and [an MPI-1 based implementation]( https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html#mpicommexecutor ). So can be deployed on different systems depending on what is available.

**Comment by jan-janssen** [comment]
Hi @jakirkham , 

Yes that is what I was using before, the idea is to simplify the process by pickling the function and sending it to the executor:
https://github.com/mpi4py/mpi4py/issues/232

Is this what you meant? Or did I misunderstand your comment? 

Best, 

Jan

**Comment by jakirkham** [comment]
Ah ok. Was wondering if there was already some exploration. Thanks for sharing 🙂

The context on the origin and different design decisions is interesting as well.
